steps:
  # Install Node.js dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['ci']

  # Build Next.js application
  - name: 'node:20'
    entrypoint: npm
    args: ['run', 'build']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: 
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'
      - '--project=inspiration-board-ig'

options:
  logging: CLOUD_LOGGING_ONLY

timeout: '1200s'
